# Generated by Django 4.0.6 on 2022-08-05 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_tn', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='place_pics/tn/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_tn', to='places.place')),
            ],
        ),
    ]
