# Generated by Django 4.0.6 on 2022-08-07 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_reservation_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='PlaceImage',
        ),
    ]
