# Generated by Django 4.0.6 on 2022-08-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_rename_image_placeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeimage',
            name='image_tn',
        ),
        migrations.AddField(
            model_name='place',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', upload_to='place_pics/tn/'),
        ),
    ]
