# Generated by Django 4.0.6 on 2022-08-07 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_remove_placeimage_image_tn_place_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='thumbnail',
        ),
    ]
