# Generated by Django 4.0.6 on 2022-08-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(None, '----'), ('Place Owner', 'Place Owner'), ('Costumer', 'Costumer')], default='0', max_length=11),
        ),
    ]
